# Generated by Django 3.2.18 on 2023-04-13 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=50)),
                ('degree_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('gpa', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('disambiguator', models.CharField(blank=True, default='', max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
                ('email_id', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='ProficiencyLevel',
            fields=[
                ('proficiency_id', models.AutoField(primary_key=True, serialize=False)),
                ('proficiency', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'ProficiencyLevel',
                'verbose_name_plural': 'ProficiencyLevel',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('persons', models.ManyToManyField(to='myportfolio.Person')),
                ('proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='myportfolio.proficiencylevel')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['skill_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('description', models.TextField()),
                ('persons', models.ManyToManyField(to='myportfolio.Person')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddConstraint(
            model_name='proficiencylevel',
            constraint=models.UniqueConstraint(fields=('proficiency',), name='unique_proficiency'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'disambiguator'), name='unique_person'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(fields=('company_name', 'start_date'), name='unique_company'),
        ),
        migrations.AddField(
            model_name='education',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education', to='myportfolio.person'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('skill_name', 'proficiency'), name='unique_skill'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('project_title',), name='unique_project'),
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.UniqueConstraint(fields=('school_name', 'degree_name', 'person_id'), name='unique_school'),
        ),
    ]
