# Generated by Django 3.2.18 on 2023-04-14 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_auto_20230414_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='myportfolio.school'),
            preserve_default=False,
        ),
    ]
