# Generated by Django 3.2.18 on 2023-04-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_remove_education_school_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='education',
            name='unique_school',
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.UniqueConstraint(fields=('school', 'degree_name', 'person_id'), name='unique_school'),
        ),
    ]
