# Generated by Django 3.2.18 on 2023-04-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_auto_20230414_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
