# Generated by Django 3.2.18 on 2023-04-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_remove_education_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
