# Generated by Django 3.2.18 on 2023-04-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0009_education_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='school_name',
        ),
    ]
