# Generated by Django 3.2.18 on 2023-04-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0011_education_school_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='school_test',
        ),
    ]
