# Generated by Django 3.2.18 on 2023-04-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0012_remove_education_school_test'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='experience',
            name='unique_company',
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(fields=('company_name', 'start_date', 'person_id'), name='unique_company'),
        ),
    ]
